services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  backend:
    image: xrays351/boda-backend:latest
    container_name: twendego-backend
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    restart: unless-stopped

  frontend:
    image: xrays351/boda-frontend:latest
    container_name: twendego-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped