name: CD - Build and Push to Docker Hub

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./django-backend
          file: ./django-backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/boda-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/boda-backend:${{ github.sha }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/boda-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/boda-frontend:${{ github.sha }}

      - name: Deployment Summary
        run: |
          echo "✅ Deployment Completed Successfully!"
          echo "📦 Images pushed:"
          echo " - ${{ secrets.DOCKER_USERNAME }}/boda-frontend:latest"
          echo " - ${{ secrets.DOCKER_USERNAME }}/boda-backend:latest"
